# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1560cf47ff96472ff3b64e2935a8ce6d088e2e610b8584fbff2e63bf0f8cf4820cd63a0d4447f6d7da02208f6bfd4e1c2f08c67f376598c7f5df37194058b290

test:
  secret_key_base: 2897821f8e4402bf6a9c6871456c3364e739ce3e3d9e0ccba2a7ab1a3ce06f062c438ceea3b78338eb5cb074318485758442bb413f2fe7070b02f0101714ea9b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
